### ISSUE TITLE
BEHAT updates

### ISSUE THREAD

**Issue by joemewes** [4AllDigital/DruDockCli#150]
docker-compose command fails

```
Output:                                                                                                                                                                                        
  ================                                                                                                                                                                               
  Error Output:                                                                                                                                                                                  
  ================                                                                                                                                                                               
  Traceback (most recent call last):                                                                                                                                                             
    File "docker-compose", line 3, in <module>                                                                                                                                                   
    File "compose/cli/main.py", line 68, in main                                                                                                                                                 
    File "compose/cli/main.py", line 118, in perform_command                                                                                                                                     
    File "compose/cli/main.py", line 454, in exec_command                                                                                                                                        
    File "site-packages/dockerpty/pty.py", line 338, in start                                                                                                                                    
    File "site-packages/dockerpty/io.py", line 32, in set_blocking                                                                                                                               
  ValueError: file descriptor cannot be a negative integer (-1)                                                                                                                                  
  Failed to execute script docker-compose         
```

can be fixed by adding `-T` to the exec command

**Comment by joemewes** [comment]
Behat drush config needs updating 

```
$aliases['drudock'] = array (
  'uri' => 'http://default',
  'root' => '/app/www',
  'remote-host' => 'php',
  'remote-user' => 'root',
  'ssh-options' => '-i ~/.ssh/dockerdev', // optional if required
);
```

should also remove ssh-options and setup default id_rsa key between BEHAT -> PHP containers

**Comment by joemewes** [comment]
resolve as part of BEHAT refactor : https://github.com/4AllDigital/DruDockCli/issues/81

**Comment by joemewes** [comment]
converted to task.
